//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlersOfCatan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettlersOfCatan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place settlement here.
        /// </summary>
        internal static string badSettlementLocation {
            get {
                return ResourceManager.GetString("badSettlementLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        internal static string brick {
            get {
                return ResourceManager.GetString("brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Card.
        /// </summary>
        internal static string buyCard {
            get {
                return ResourceManager.GetString("buyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must click neighboring vertex!.
        /// </summary>
        internal static string clickNeighborVertex {
            get {
                return ResourceManager.GetString("clickNeighborVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must click on the robber.
        /// </summary>
        internal static string clickRobber {
            get {
                return ResourceManager.GetString("clickRobber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string congratulations {
            get {
                return ResourceManager.GetString("congratulations", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap desert_texture {
            get {
                object obj = ResourceManager.GetObject("desert_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        internal static string endTurn {
            get {
                return ResourceManager.GetString("endTurn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap english {
            get {
                object obj = ResourceManager.GetObject("english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap field_texture {
            get {
                object obj = ResourceManager.GetObject("field_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string fields {
            get {
                return ResourceManager.GetString("fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forests.
        /// </summary>
        internal static string forests {
            get {
                return ResourceManager.GetString("forests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Setup.
        /// </summary>
        internal static string gameSetup {
            get {
                return ResourceManager.GetString("gameSetup", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap german {
            get {
                object obj = ResourceManager.GetObject("german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        internal static string grain {
            get {
                return ResourceManager.GetString("grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hills.
        /// </summary>
        internal static string hills {
            get {
                return ResourceManager.GetString("hills", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hills_texture {
            get {
                object obj = ResourceManager.GetObject("hills_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Resources.
        /// </summary>
        internal static string insufficientResources {
            get {
                return ResourceManager.GetString("insufficientResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid location.
        /// </summary>
        internal static string invalidLocation {
            get {
                return ResourceManager.GetString("invalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string knight {
            get {
                return ResourceManager.GetString("knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest Army.
        /// </summary>
        internal static string largestArmy {
            get {
                return ResourceManager.GetString("largestArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game.
        /// </summary>
        internal static string loadGame {
            get {
                return ResourceManager.GetString("loadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Road.
        /// </summary>
        internal static string longestRoad {
            get {
                return ResourceManager.GetString("longestRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopoly.
        /// </summary>
        internal static string monopoly {
            get {
                return ResourceManager.GetString("monopoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountains.
        /// </summary>
        internal static string mountains {
            get {
                return ResourceManager.GetString("mountains", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mountains_texture {
            get {
                object obj = ResourceManager.GetObject("mountains_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Robber.
        /// </summary>
        internal static string moveRobber {
            get {
                return ResourceManager.GetString("moveRobber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must move the robber before you can end your turn.
        /// </summary>
        internal static string mustMoveRobber {
            get {
                return ResourceManager.GetString("mustMoveRobber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough resources.
        /// </summary>
        internal static string notEnoughResources {
            get {
                return ResourceManager.GetString("notEnoughResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Players:.
        /// </summary>
        internal static string numberOfPlayers {
            get {
                return ResourceManager.GetString("numberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        internal static string ore {
            get {
                return ResourceManager.GetString("ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        internal static string owned {
            get {
                return ResourceManager.GetString("owned", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pasture_texture {
            get {
                object obj = ResourceManager.GetObject("pasture_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastures.
        /// </summary>
        internal static string pastures {
            get {
                return ResourceManager.GetString("pastures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place City.
        /// </summary>
        internal static string placeCity {
            get {
                return ResourceManager.GetString("placeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Road.
        /// </summary>
        internal static string placeRoad {
            get {
                return ResourceManager.GetString("placeRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Village.
        /// </summary>
        internal static string placeVillage {
            get {
                return ResourceManager.GetString("placeVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string road {
            get {
                return ResourceManager.GetString("road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road already exists here!.
        /// </summary>
        internal static string roadAlreadyHere {
            get {
                return ResourceManager.GetString("roadAlreadyHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Building.
        /// </summary>
        internal static string roadBuilding {
            get {
                return ResourceManager.GetString("roadBuilding", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap robber {
            get {
                object obj = ResourceManager.GetObject("robber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robber.
        /// </summary>
        internal static string robberString {
            get {
                return ResourceManager.GetString("robberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\rules.pdf.
        /// </summary>
        internal static string rulesPDF {
            get {
                return ResourceManager.GetString("rulesPDF", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sea_texture {
            get {
                object obj = ResourceManager.GetObject("sea_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language:.
        /// </summary>
        internal static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlements.
        /// </summary>
        internal static string settlements {
            get {
                return ResourceManager.GetString("settlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string soldier {
            get {
                return ResourceManager.GetString("soldier", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap startBackground {
            get {
                object obj = ResourceManager.GetObject("startBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlers of C#tan.
        /// </summary>
        internal static string startTitle {
            get {
                return ResourceManager.GetString("startTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Trade.
        /// </summary>
        internal static string toTrade {
            get {
                return ResourceManager.GetString("toTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string trade {
            get {
                return ResourceManager.GetString("trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Player.
        /// </summary>
        internal static string tradePlayer {
            get {
                return ResourceManager.GetString("tradePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Port.
        /// </summary>
        internal static string tradePort {
            get {
                return ResourceManager.GetString("tradePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap victory {
            get {
                object obj = ResourceManager.GetObject("victory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory point.
        /// </summary>
        internal static string victoryPoint {
            get {
                return ResourceManager.GetString("victoryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        internal static string village {
            get {
                return ResourceManager.GetString("village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumber.
        /// </summary>
        internal static string wood {
            get {
                return ResourceManager.GetString("wood", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap woods_texture {
            get {
                object obj = ResourceManager.GetObject("woods_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wool.
        /// </summary>
        internal static string wool {
            get {
                return ResourceManager.GetString("wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Plenty.
        /// </summary>
        internal static string yearOfPlenty {
            get {
                return ResourceManager.GetString("yearOfPlenty", resourceCulture);
            }
        }
    }
}
